algoritmo "Exercicio Matriz 01"

var
Cursos: vetor [0..1, 0..2] de caracter

inicio

escreva ("Digite o nome do curso: ")
leia (cursos[0,0])

escreva ("Digite o nome do curso: ")
leia (cursos[0,1])

escreva ("Digite o nome do curso: ")
leia (cursos[0,2])

escreva ("Digite o nome do curso: ")
leia (cursos[1,0])

escreva ("Digite o nome do curso: ")
leia (cursos[1,1])

escreva ("Digite o nome do curso: ")
leia (curso[1,2])


fimalgoritmo
